package ba.unsa.etf.rpr.business;

import ba.unsa.etf.rpr.dao.DaoFactory;
import ba.unsa.etf.rpr.domain.Departments;
import ba.unsa.etf.rpr.exceptions.EmployeeException;

import java.util.List;

/**
 * @author Kadric Nerma
 * Business Logic Layer for management of Departments
 */
public class DepartmentManager {
    /**
     * A method to check the validity of a name
     *
     * @param name
     * @throws EmployeeException
     */
    public void validName(String name) throws EmployeeException {
        if (name.length() > 45 || name == null || name.length() < 2)
            throw new EmployeeException("Name of department must be between 2 and 45 chars");

    }

    public Departments add(Departments d) throws EmployeeException {
        if (d.getId() != 0) throw new EmployeeException("ID is autogenerated. Cannot add department.");
        validName(d.getDepname());
        try {
            return DaoFactory.departmentDao().add(d);
        } catch (EmployeeException e) {
            if (e.getMessage().contains("UQ_NAME")) {
                throw new EmployeeException("This department name already exists");
            }
            throw e;
        }
    }

    public Departments update(Departments d) throws EmployeeException {
        validName(d.getDepname());
        return DaoFactory.departmentDao().update(d);
    }

    public List<Departments> getAll() throws EmployeeException {
        return DaoFactory.departmentDao().getAll();
    }

    public void delete(int depId) throws EmployeeException {
        try {
            DaoFactory.departmentDao().delete(depId);
        } catch (EmployeeException e) {
            if (e.getMessage().contains("FOREIGN KEY")) {
                throw new EmployeeException("Cannot delete department which is related to employees. You must delete employees of that department first, then delete department.");
            }
            throw e;
        }
    }
}
