package ba.unsa.etf.rpr.business;

import ba.unsa.etf.rpr.dao.DaoFactory;
import ba.unsa.etf.rpr.domain.Department;
import ba.unsa.etf.rpr.exceptions.EmployeeException;

public class DepartmentManager {
    public void delete(int depid) throws EmployeeException{
        try{
            DaoFactory.departmentDao().delete(depid);
        }catch (EmployeeException e){
            if(e.getMessage().contains("FOREIGN KEY")){
                throw new EmployeeException("You must first delete related employees before deleting department!");
            }
            throw e;
        }
    }
    public void validname(String name) throws EmployeeException{
        if(name.length()>45 || name==null || name.length()<2) throw new EmployeeException("Name of department must be between 2 and 45 chars");

    }
    public Department add(Department d)throws EmployeeException{
        if(d.getId()!=0) throw new EmployeeException("ID is autogenerated. Cannot add department.");
        validname(d.getDepname());
        try{
            return DaoFactory.departmentDao().add(d);
        }catch (EmployeeException e){
            if(e.getMessage().contains("UQ_NAME")){
                throw new EmployeeException("This department name already exists");
            } throw e;
        }
    }
}
