package ba.unsa.etf.rpr.business;

import ba.unsa.etf.rpr.dao.DaoFactory;
import ba.unsa.etf.rpr.domain.Employee;
import ba.unsa.etf.rpr.exceptions.EmployeeException;

import java.util.List;

/**
 * @author Kadric Nerma
 * Business Logic Layer for management of Employees
 */
public class EmployeeManager {
    /**
     * A method to check the validity of a name
     *
     * @param name
     * @throws EmployeeException
     */
    public void validName(String name) throws EmployeeException {
        if (name.length() > 45 || name == null || name.length() < 2)
            throw new EmployeeException("Name of employee must be between 2 and 45 chars");

    }

    public static void validSalary(int s) throws EmployeeException {
        if (s <= 0) {
            throw new EmployeeException("Employee must have salary");
        } else if (s > 10000) throw new EmployeeException("Employee cannot have salary greater than 10000");


    }

    public Employee add(Employee e) throws EmployeeException {
        if (e.getId() != 0) throw new EmployeeException("ID is autogenerated. Cannot add department.");
        validName(e.getFirst_name());
        validName(e.getLast_name());
        validName(e.getAddress());
        validSalary(e.getPayoff());
        try {
            return DaoFactory.employeeDao().add(e);
        } catch (EmployeeException ee) {
            if (ee.getMessage().contains("UQ_NAME")) {
                throw new EmployeeException("This employee already exists");
            }
            throw ee;
        }
    }

    public Employee update(Employee e) throws EmployeeException {
        validName(e.getFirst_name());
        validName(e.getLast_name());
        validName(e.getAddress());
        validSalary(e.getPayoff());
        return DaoFactory.employeeDao().update(e);
    }

    public List<Employee> getAll() throws EmployeeException {
        return DaoFactory.employeeDao().getAll();
    }

    public Employee getById(Integer employeeId) throws EmployeeException {
        return DaoFactory.employeeDao().getById(employeeId);
    }

    public void delete(int eId) throws EmployeeException {
        DaoFactory.employeeDao().delete(eId);
    }

    public List<Employee> getByProject(Integer projectId) throws EmployeeException {
        return DaoFactory.employeeDao().searchByProject(projectId);
    }

    public List<Employee> getByHireDate() throws EmployeeException {
        return DaoFactory.employeeDao().getByHireDate();
    }
}

