package ba.unsa.etf.rpr.business;

import ba.unsa.etf.rpr.dao.Dao;
import ba.unsa.etf.rpr.dao.DaoFactory;
import ba.unsa.etf.rpr.domain.Departments;
import ba.unsa.etf.rpr.domain.Employee;
import ba.unsa.etf.rpr.exceptions.EmployeeException;

import java.util.List;

public class EmployeeManager {

    public void validname(String name) throws EmployeeException {
        if (name.length() > 45 || name == null || name.length() < 2)
            throw new EmployeeException("Name of employee must be between 2 and 45 chars");

    }

    public Employee add(Employee e) throws EmployeeException {
        if (e.getId() != 0) throw new EmployeeException("ID is autogenerated. Cannot add department.");
        validname(e.getFirst_name());
        validname(e.getLast_name());
        validname(e.getAddress());
        try {
            return DaoFactory.employeeDao().add(e);
        } catch (EmployeeException ee) {
            if (ee.getMessage().contains("UQ_NAME")) {
                throw new EmployeeException("This employee already exists");
            }
            throw ee;
        }
    }

    public Employee update(Employee e) throws EmployeeException {
        validname(e.getFirst_name());
        validname(e.getLast_name());
        validname(e.getAddress());
        return DaoFactory.employeeDao().update(e);
    }

    public List<Employee> getAll() throws EmployeeException {
        return DaoFactory.employeeDao().getAll();
    }
     public Employee getById(Integer employeeId) throws EmployeeException{
        return DaoFactory.employeeDao().getById(employeeId);
     }
    public void delete(int eId) throws EmployeeException {
        DaoFactory.employeeDao().delete(eId);
    }
    public List<Employee> getByProject(Integer projectId) throws EmployeeException {
        return DaoFactory.employeeDao().searchByProject(projectId);
    }

    public List<Employee> getByHireDate() throws EmployeeException {
        return DaoFactory.employeeDao().getByHireDate();
    }
}

