package ba.unsa.etf.rpr.business;

import ba.unsa.etf.rpr.dao.DaoFactory;
import ba.unsa.etf.rpr.domain.Project;
import ba.unsa.etf.rpr.exceptions.EmployeeException;

import java.util.List;

public class ProjectManager {
    public void validname(String name) throws EmployeeException {
        if(name.length()>45 || name==null || name.length()<2) throw new EmployeeException("Name of project must be between 2 and 45 chars");

    }
    public Project add(Project p)throws EmployeeException{
        if(p.getId()!=0) throw new EmployeeException("ID is autogenerated. Cannot add project.");
        validname(p.getProject_name());
        try{
            return DaoFactory.projectDao().add(p);
        }catch (EmployeeException e){
            if(e.getMessage().contains("UQ_NAME")){
                throw new EmployeeException("This project name already exists");
            } throw e;
        }
    }
    public List<Project> getAll() throws EmployeeException{
        return DaoFactory.projectDao().getAll();
    }
    public void delete(int pId) throws  EmployeeException{
        try{
            DaoFactory.projectDao().delete(pId);

        }catch (EmployeeException e){
            if(e.getMessage().contains("FOREIGN KEY")){
                throw new EmployeeException("Cannot delete project which is related to employees. You must delete employees of that project first, then delete project.");

            }
            throw e;
        }
    }
}
