package ba.unsa.etf.rpr.business;

import ba.unsa.etf.rpr.dao.DaoFactory;
import ba.unsa.etf.rpr.dao.DepartmentsDAOSQLImpl;
import ba.unsa.etf.rpr.domain.Departments;
import ba.unsa.etf.rpr.exceptions.EmployeeException;
import org.apache.commons.lang3.RandomStringUtils;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.MockedStatic;
import org.mockito.Mockito;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertNull;
import static org.mockito.Mockito.when;

public class DepartmentManagerTest {
    private DepartmentManager departmentManager;
    private Departments d;
    private DepartmentsDAOSQLImpl departmentsDAOSQL;
    private List<Departments> departments;

    @BeforeEach
    public void initializeObj() {
        departmentManager = Mockito.mock(DepartmentManager.class);
        d = new Departments();
        d.setId(1);
        d.setDepname("Backend-developer");
        d.setHourlypay(15);
        departmentsDAOSQL = Mockito.mock(DepartmentsDAOSQLImpl.class);
        departments = new ArrayList<>();
        departments.addAll(Arrays.asList(new Departments( "Marketing", 10),
                new Departments( "Software archi", 20)));

    }
    @Test
    void validName() throws EmployeeException {
        String n1 = "UI/UX";
        try {
          Mockito.doCallRealMethod().when(departmentManager).validName(n1);
        } catch (EmployeeException e) {
            e.printStackTrace();
            Assertions.assertTrue(false);
        }
        String n2= "A";
        Mockito.doCallRealMethod().when(departmentManager).validName(n2);
       EmployeeException e=Assertions.assertThrows(EmployeeException.class, ()->{departmentManager.validName(n2);}, "Name of department must be between 2 and 45 chars");
       Assertions.assertEquals("Name of department must be between 2 and 45 chars", e.getMessage());
        String n3=RandomStringUtils.randomAlphabetic(55);
        Mockito.doCallRealMethod().when(departmentManager).validName(n3);
        EmployeeException ee=Assertions.assertThrows(EmployeeException.class, ()->{departmentManager.validName(n3);}, "Name of department must be between 2 and 45 chars");
        Assertions.assertEquals("Name of department must be between 2 and 45 chars", ee.getMessage());
    }
    @Test
    void add()throws EmployeeException{
        MockedStatic<DaoFactory> daoFactoryMockedStatic=Mockito.mockStatic(DaoFactory.class);
        daoFactoryMockedStatic.when(DaoFactory::departmentDao).thenReturn(departmentsDAOSQL);
        when(DaoFactory.departmentDao().getAll()).thenReturn(departments);
        Mockito.doCallRealMethod().when(departmentManager).add(d);
        EmployeeException exception=Assertions.assertThrows(EmployeeException.class,()->{departmentManager.add(d);},"ID is autogenerated. Cannot add department.");
        Assertions.assertEquals("ID is autogenerated. Cannot add department.", exception.getMessage());
        daoFactoryMockedStatic.verify(DaoFactory::departmentDao);
        Mockito.verify(departmentManager).add(d);
        daoFactoryMockedStatic.close();
    }
    @Test
    void addNewDepTest() throws EmployeeException {
       Departments departments1=new Departments("QA Manager",11);
       departmentManager.add(departments1);
       Assertions.assertTrue(true);
       Mockito.verify(departmentManager).add(departments1);
    }


      @Test
       void testAdd() throws EmployeeException{
        MockedStatic<DaoFactory> daoFactoryMockedStatic = Mockito.mockStatic(DaoFactory.class);
        DepartmentsDAOSQLImpl depDao = Mockito.mock(DepartmentsDAOSQLImpl.class);
        daoFactoryMockedStatic.when(DaoFactory::departmentDao).thenReturn(depDao);
        when(depDao.add(d)).thenReturn(d);
        departmentManager.add(d);
        Assertions.assertTrue(true);
        daoFactoryMockedStatic.close();
       }
      @Test
    void testUpdate() throws EmployeeException{
    MockedStatic<DaoFactory> daoFactoryMockedStatic = Mockito.mockStatic(DaoFactory.class);
    DepartmentsDAOSQLImpl depDao = Mockito.mock(DepartmentsDAOSQLImpl.class);
    daoFactoryMockedStatic.when(DaoFactory::departmentDao).thenReturn(depDao);
    d.setHourlypay(10);
    when(depDao.update(d)).thenReturn(d);
    departmentManager.update(d);
    Assertions.assertTrue(true);
    daoFactoryMockedStatic.close();
     }
     @Test
    void test() throws EmployeeException{
        Departments dep=departmentsDAOSQL.ReturnDepartmentForId(-10);
        assertNull(dep);
     }
}
