package ba.unsa.etf.rpr.business;

import ba.unsa.etf.rpr.dao.DaoFactory;
import ba.unsa.etf.rpr.dao.DepartmentsDAOSQLImpl;
import ba.unsa.etf.rpr.domain.Departments;
import ba.unsa.etf.rpr.exceptions.EmployeeException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockedStatic;
import org.mockito.Mockito;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static org.mockito.Mockito.when;

public class DepartmentManagerTest {
    private DepartmentManager departmentManager;
    private Departments d;
    private DepartmentsDAOSQLImpl departmentsDAOSQL;
    private List<Departments> departments;

    @BeforeEach
    public void initializeObj() {
        departmentManager = new DepartmentManager();
        Mockito.mock(DepartmentManager.class);
        d = new Departments();
        d.setDepname("Backend-developer");
        d.setHourlypay(15);
        d.setId(1);
        departmentsDAOSQL = Mockito.mock(DepartmentsDAOSQLImpl.class);
        departments = new ArrayList<>();
        departments.addAll(Arrays.asList(new Departments( "Marketing", 10),
                new Departments( "Software archi", 20)));

    }

    @Test
    void addNewDepTest() throws EmployeeException {
        MockedStatic<DaoFactory> daoFactoryMockedStatic = Mockito.mockStatic(DaoFactory.class);

        DepartmentsDAOSQLImpl depDao = Mockito.mock(DepartmentsDAOSQLImpl.class);
        daoFactoryMockedStatic.when(DaoFactory::departmentDao).thenReturn(depDao);

        when(depDao.add(d)).thenReturn(d);

        departmentManager.add(d);
        Assertions.assertTrue(true);
    }

    @Test
    void UpdateDepTest() throws EmployeeException {
        d.setHourlypay(23);
        MockedStatic<DaoFactory> daoFactoryMockedStatic = Mockito.mockStatic(DaoFactory.class);

        DepartmentsDAOSQLImpl depDao = Mockito.mock(DepartmentsDAOSQLImpl.class);
        daoFactoryMockedStatic.when(DaoFactory::departmentDao).thenReturn(depDao);

        when(depDao.update(d)).thenReturn(d);

        departmentManager.update(d);
        Assertions.assertTrue(true);
    }
@Test
void add()throws EmployeeException{
    MockedStatic<DaoFactory> daoFactoryMockedStatic=Mockito.mockStatic(DaoFactory.class);
    daoFactoryMockedStatic.when(DaoFactory::departmentDao).thenReturn(departmentsDAOSQL);
    when(DaoFactory.departmentDao().getAll()).thenReturn(departments);
    Mockito.doCallRealMethod().when(departmentManager).add(d);
    EmployeeException exception=Assertions.assertThrows(EmployeeException.class,()->{departmentManager.add(d);},"ID is autogenerated. Cannot add department.");
    Assertions.assertEquals("ID is autogenerated. Cannot add department.", exception.getMessage());
daoFactoryMockedStatic.verify(DaoFactory::departmentDao);
Mockito.verify(departmentManager).add(d);
daoFactoryMockedStatic.close();
    }
    @Test
    void addDep()throws EmployeeException {
      Departments newDep = new Departments(2, "GameDeveloper", 25);
      newDep.setId(0);
      departmentManager.add(newDep);
        Assertions.assertTrue(true);
        Mockito.verify(departmentManager).add(newDep);
    }
}
