package ba.unsa.etf.rpr.business;

import ba.unsa.etf.rpr.dao.DaoFactory;
import ba.unsa.etf.rpr.dao.EmployeeDAOSQLImpl;
import ba.unsa.etf.rpr.domain.Departments;
import ba.unsa.etf.rpr.domain.Employee;
import ba.unsa.etf.rpr.domain.Project;
import ba.unsa.etf.rpr.exceptions.EmployeeException;
import org.apache.commons.lang3.RandomStringUtils;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.MockedStatic;
import org.mockito.Mockito;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static org.mockito.Mockito.when;

public class EmployeeManagerTest {
    private EmployeeManager employeeManager;
    private Employee e;
    private EmployeeDAOSQLImpl employeeDAOSQL;
    private List<Employee> employees;

    @BeforeEach
    public void initializeObj(){
        employeeManager= new EmployeeManager();//Mockito.mock(EmployeeManager.class);
        e=new Employee();
        e.setFirst_name("Ivana");
        e.setLast_name("Marc");
        e.setAddress("street5.B");
        e.setHire_date(LocalDate.now());
        e.setId(40);
        e.setPayoff(1000);
        e.setEdu("Bachelor");
        Project p=new Project();
        p.setId(200);
        e.setProject(p);
        Departments d=new Departments();
        d.setId(30);
        e.setDepartment(d);
        employeeDAOSQL=Mockito.mock(EmployeeDAOSQLImpl.class);
        employees=new ArrayList<>();
        employees.addAll(Arrays.asList(new Employee(51,"Zana","Jack","street22.D",LocalDate.now(),new Departments(30),new Project(202),"Master",2000),
                new Employee(52,"Clare","Jade","street25.D",LocalDate.now(),new Departments(20),new Project(202),"Master",2000)));

    }
    @Test
    void validName() {

        String n1 = "Zana";
        String n2 = "Jack";
        try {
            employeeManager.validname(n1);
            employeeManager.validname(n2);
        } catch (EmployeeException e) {
            e.printStackTrace();
            Assertions.assertTrue(false);
        }
        String incorrectn = "A";
        Assertions.assertThrows(EmployeeException.class, () -> {
            employeeManager.validname(incorrectn);
        }, "Name of employee must be between 2 and 45 chars");
        String inc = RandomStringUtils.randomAlphabetic(50);
        Assertions.assertThrows(EmployeeException.class, () -> {
            employeeManager.validname(inc);
        }, "Name of employee must be between 2 and 45 chars");

    }
    @Test
    void add() throws EmployeeException{
        MockedStatic<DaoFactory> daoFactoryMockedStatic=Mockito.mockStatic(DaoFactory.class);
        daoFactoryMockedStatic.when(DaoFactory::employeeDao).thenReturn(employeeDAOSQL);
        when(DaoFactory.employeeDao().getAll()).thenReturn(employees);
        Mockito.doCallRealMethod().when(employeeManager).add(e);
        EmployeeException emp=Assertions.assertThrows(EmployeeException.class, ()->{
            employeeManager.add(e);}, "ID is autogenerated. Cannot add department.");
        Assertions.assertEquals("ID is autogenerated. Cannot add department.", emp.getMessage());
        daoFactoryMockedStatic.verify(DaoFactory::employeeDao);
        Mockito.verify(employeeManager).add(e);
        daoFactoryMockedStatic.close();
        }
        @Test
    void addNewEmp() throws EmployeeException{
        Employee e=new Employee(55,"Zina","Marrs","street278.D",LocalDate.now(),new Departments(10),new Project(201),"Bachelor",1000);
        e.setId(0);

        MockedStatic<DaoFactory> daoFactoryMockedStatic=Mockito.mockStatic(DaoFactory.class);

        EmployeeDAOSQLImpl employeeDao=Mockito.mock(EmployeeDAOSQLImpl.class);
        daoFactoryMockedStatic.when(DaoFactory::employeeDao).thenReturn(employeeDao);

        when(employeeDao.add(e)).thenReturn(e);

        employeeManager.add(e);
        Assertions.assertTrue(true);
        }
    }


